
name: docker

on:
  workflow_dispatch:
    
jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          image: tonistiigi/binfmt:qemu-v7.0.0-28

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure image tag
        id: image_tag
        run: |
          echo "image_tag=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: login to aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ZYY_ALICLOUD_USER }}
          password: ${{ secrets.ZYY_ALICLOUD_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/zyyinternal/o11ybench:latest
            registry.cn-hangzhou.aliyuncs.com/zyyinternal/o11ybench:${{ env.image_tag }}
